# Generated by Django 4.1.3 on 2022-12-22 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppRutinas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posteo',
            name='imagen',
            field=models.ImageField(default=1, upload_to='media'),
            preserve_default=False,
        ),
    ]
