# Generated by Django 4.1.3 on 2022-12-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppRutinas', '0002_posteo_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='posteo',
            name='fecha',
            field=models.DateTimeField(default='2022-01-01'),
        ),
    ]
